// Unqork components by tray type and label, with the color group each belongs to.
export interface CatalogEntry { type: string; label: string; group: string; icon: string; family: string; deprecated?: boolean }
export const components: CatalogEntry[] = [
  {type:'selectboxes',label:'Checkboxes',group:'Primary Fields',icon:'list-checks',family:'inputs'},
  {type:'dateinput',label:'Date Input',group:'Primary Fields',icon:'calendar',family:'inputs'},
  {type:'basicDropdown',label:'Dropdown',group:'Primary Fields',icon:'square-chevron-down',family:'inputs'},
  {type:'select',label:'Multi-Select Dropdown',group:'Primary Fields',icon:'chevron-down',family:'inputs'},
  {type:'number',label:'Number',group:'Primary Fields',icon:'hash',family:'inputs'},
  {type:'radio',label:'Radio Buttons',group:'Primary Fields',icon:'circle-dot',family:'inputs'},
  {type:'checkboxv2',label:'Single Checkbox',group:'Primary Fields',icon:'square-check-big',family:'inputs'},
  {type:'textarea',label:'Text Area',group:'Primary Fields',icon:'text-align-start',family:'inputs'},
  {type:'textfield',label:'Text Field',group:'Primary Fields',icon:'type',family:'inputs'},
  {type:'address',label:'Address',group:'Secondary Fields',icon:'map-pin',deprecated:true,family:'inputs'},
  {type:'addressv2',label:'Address Search',group:'Secondary Fields',icon:'map-pin',family:'inputs'},
  {type:'button',label:'Button',group:'Secondary Fields',icon:'mouse-pointer-click',family:'actions'},
  {type:'email',label:'Email',group:'Secondary Fields',icon:'mail',family:'inputs'},
  {type:'hidden',label:'Hidden',group:'Secondary Fields',icon:'eye-off',family:'data'},
  {type:'phonenumber-v2',label:'Intl Phone Number',group:'Secondary Fields',icon:'phone',family:'inputs'},
  {type:'phoneNumber',label:'Phone Number',group:'Secondary Fields',icon:'phone',family:'inputs'},
  {type:'password',label:'Protected Field',group:'Secondary Fields',icon:'lock',family:'inputs'},
  {type:'signature',label:'Signature',group:'Secondary Fields',icon:'pen-tool',family:'inputs'},
  {type:'dataviewer',label:'Advanced Data Grid',group:'Display & Layout',icon:'table',family:'grids'},
  {type:'columns',label:'Columns',group:'Display & Layout',icon:'columns-2',family:'layout'},
  {type:'content',label:'Content',group:'Display & Layout',icon:'file-text',family:'content'},
  {type:'datagrid',label:'Data Grid',group:'Display & Layout',icon:'table',family:'grids'},
  {type:'dynamicGrid',label:'Dynamic Grid',group:'Display & Layout',icon:'layout-grid',family:'grids'},
  {type:'field-group',label:'Field Group',group:'Display & Layout',icon:'group',family:'layout'},
  {type:'freeFormGrid',label:'Freeform Grid',group:'Display & Layout',icon:'layout-grid',family:'grids'},
  {type:'htmlelement',label:'HTML Element',group:'Display & Layout',icon:'code',family:'content'},
  {type:'markdown',label:'Markdown',group:'Display & Layout',icon:'text-align-start',family:'content'},
  {type:'survey',label:'Matrix',group:'Display & Layout',icon:'grid-3x3',family:'grids'},
  {type:'navigation',label:'Navigation',group:'Display & Layout',icon:'navigation',family:'actions'},
  {type:'panel',label:'Panel',group:'Display & Layout',icon:'panel-top',family:'layout'},
  {type:'repeater',label:'Repeater',group:'Display & Layout',icon:'copy-plus',family:'layout'},
  {type:'richtexteditor',label:'Rich Text Editor',group:'Display & Layout',icon:'text-align-start',family:'inputs'},
  {type:'table',label:'Table',group:'Display & Layout',icon:'table',family:'layout'},
  {type:'inlineGrid',label:'Uniform Grid',group:'Display & Layout',icon:'grid-3x3',family:'grids'},
  {type:'viewgrid',label:'View Grid',group:'Display & Layout',icon:'layout-grid',family:'grids'},
  {type:'browserStorage',label:'Browser Storage',group:'Data & Event Processing',icon:'hard-drive',family:'data'},
  {type:'transformer',label:'Calculator',group:'Data & Event Processing',icon:'calculator',family:'logic'},
  {type:'checkpoint',label:'Checkpoint',group:'Data & Event Processing',icon:'flag',family:'data'},
  {type:'datamapper',label:'Data Mapper',group:'Data & Event Processing',icon:'arrow-right-left',family:'logic'},
  {type:'infotable',label:'Data Table',group:'Data & Event Processing',icon:'database',family:'data'},
  {type:'dataworkflow',label:'Data Workflow',group:'Data & Event Processing',icon:'workflow',family:'logic'},
  {type:'decision',label:'Decisions',group:'Data & Event Processing',icon:'git-branch',family:'logic'},
  {type:'file',label:'File',group:'Data & Event Processing',icon:'file-up',family:'inputs'},
  {type:'filestorage',label:'File Storage',group:'Data & Event Processing',icon:'folder',family:'data'},
  {type:'initializer',label:'Initializer',group:'Data & Event Processing',icon:'play',family:'logic'},
  {type:'plaid',label:'Plaid',group:'Data & Event Processing',icon:'landmark',family:'integrations'},
  {type:'integrator',label:'Plug-In',group:'Data & Event Processing',icon:'plug',family:'integrations'},
  {type:'timer',label:'Timer',group:'Data & Event Processing',icon:'timer',family:'logic'},
  {type:'chart',label:'Chart',group:'Charts & Graphs',icon:'chart-column',family:'charts'},
  {type:'kpi',label:'KPI',group:'Charts & Graphs',icon:'gauge',family:'charts'},
  {type:'map',label:'Map',group:'Charts & Graphs',icon:'map',family:'charts'},
  {type:'mapv2',label:'Map V2',group:'Charts & Graphs',icon:'map',family:'charts'},
  {type:'aiSummarizer',label:'AI Summarizer',group:'Agentic Pallet',icon:'sparkles',family:'logic'},
  {type:'uiBlock',label:'Simple Grid',group:'Display & Layout',icon:'puzzle',family:'grids'}
];
