const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const { chromium, firefox } = require('playwright');
const firefoxMode = process.argv.includes('--firefox');
fs.mkdirSync(path.resolve(__dirname, '../artifacts'), { recursive:true });
const root = path.resolve(__dirname, '../dist', firefoxMode ? 'firefox' : 'chrome');
const catalog = JSON.parse(fs.readFileSync(path.join(__dirname, '../docs/component-catalog.json'), 'utf8'));
const script = fs.readFileSync(path.join(root, 'content-scripts/content.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'content-scripts/content.css'), 'utf8');
const icon = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 9v12"/></svg>';
const tray = component => `<div data-tray-type="${component.type}" role="button" tabindex="0">${icon}<span>${component.label}</span><svg data-handle="true"></svg></div>`;
const card = (component, key = component.type) => `<div data-component-key="${key}" role="button" tabindex="0"><div class="header"><div class="tile">${icon}</div><div><strong>${component.label} example</strong><div class="text-2xs">${component.label === 'Plug-In' ? 'PLUGIN' : component.label.toUpperCase()}</div></div><div class="trailing"><button data-slot="popover-trigger" aria-label="1 dependencies"><span>1</span></button><button data-slot="dropdown-menu-trigger" aria-label="Actions for ${key}">⋮</button></div></div></div>`;
const fixture = `<main><aside>${catalog.components.map(tray).join('')}</aside><section>${catalog.components.map(component => card(component)).join('')}<div data-component-key="unknown">${icon}<div class="text-2xs">UNKNOWN TYPE</div></div><div data-component-key="imported"><a>Module: Example</a>${card(catalog.components[0], 'nested-child')}</div></section></main>`;
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
assert.deepEqual(manifest.permissions, ['storage', 'activeTab', 'scripting']);
for (const file of [...manifest.content_scripts[0].js, ...manifest.content_scripts[0].css, manifest.action.default_popup]) assert(fs.existsSync(path.join(root, file)));
const dom = new JSDOM(fixture, { url:'https://american-equity-staging.unqork.io/ide/builder/test', runScripts:'outside-only', pretendToBeVisual:true });
let change;
let testObserver;
const NativeObserver = dom.window.MutationObserver;
dom.window.MutationObserver = class extends NativeObserver {
  constructor(callback) { super(callback); testObserver = this; }
};
dom.window[firefoxMode ? 'browser' : 'chrome'] = { storage: { local: { get:async () => ({}) }, onChanged: { addListener: listener => { change = listener; } } } };
const settle = () => new Promise(resolve => setTimeout(resolve, 70));
const query = selector => dom.window.document.querySelector(selector);
async function settings(value) { change({ appearance: { newValue:value } }, 'local'); await settle(); }
async function rowLayout(value) { change({ rowLayout: { newValue:value } }, 'local'); await settle(); }
const containerHeader = (label, key) => `<div data-slot="collapsible-trigger" data-panel-open="" data-component-key="${key}" class="header"><div class="tile">${icon}</div><div><strong>${key}</strong><div class="text-2xs">${label}</div></div><div class="trailing"><button data-slot="dropdown-menu-trigger" aria-label="Actions for ${key}">⋮</button></div></div>`;
// Read-only modules, such as imports, render frames without the drag attributes.
const containerFrame = (label, key, body, draggable = true) => `<div id="${key}-wrap"><div data-slot="collapsible"><div${draggable ? ' aria-roledescription="draggable"' : ''} id="${key}-frame">${containerHeader(label, key)}<div data-slot="collapsible-content"><div id="${key}-body">${body}</div></div></div></div></div>`;
const nestedContainers = containerFrame('PANEL', 'outer', containerFrame('FIELD GROUP', 'inner', card(catalog.components[0], 'inner-leaf')) + containerFrame('CUSTOM WIDGET', 'custom', '', false)) + '<div data-slot="collapsible"><div data-slot="collapsible-trigger" id="context-trigger"><svg></svg>Context1</div><div data-slot="collapsible-content"><div id="context-body"></div></div></div>';
const allContainers = { containerSpacing:true, containerHeaders:true, containerGuides:true, containerDepth:true, containerSticky:true, containerEnd:true };
const allLeft = { enabled:true, icon:'left', name:'left', type:'left', chip:'left', actions:'left' };
const middle = { enabled:true, icon:'left', name:'left', type:'middle', chip:'middle', actions:'right' };
(async () => {
  dom.window.eval(script);
  await settle();
  assert.equal(dom.window.document.querySelectorAll('[data-uq-family]').length, 109);
  assert.equal(query('[data-tray-type="integrator"]').dataset.uqFamily, 'integrations');
  assert.equal(query('[data-component-key="integrator"]').dataset.uqFamily, 'integrations');
  assert(!query('[data-component-key="unknown"]').hasAttribute('data-uq-family'));
  assert(!query('[data-component-key="imported"]').hasAttribute('data-uq-family'));
  assert(!query('[data-handle]').hasAttribute('data-uq-icon'));
  const existing = query('[data-component-key="number"]');
  const svg = existing.querySelector('svg');
  const shape = svg.innerHTML;
  let clicked = false;
  existing.addEventListener('click', () => { clicked = true; });
  existing.click();
  assert(clicked);
  assert(!query('[data-uq-compact]'));
  const compactOnly = { compact:true, icons:false, tiles:false, labels:false, symbols:false };
  await settings(compactOnly);
  assert.equal(existing.dataset.uqCompact, 'canvas');
  assert.equal(query('[data-tray-type="number"]').dataset.uqCompact, 'tray');
  assert(!query('[data-component-key="imported"]').hasAttribute('data-uq-compact'));
  assert(!svg.hasAttribute('data-uq-icon'));
  existing.querySelector('.text-2xs').textContent = 'CUSTOM TYPE';
  await settle();
  assert.equal(existing.dataset.uqCompact, 'canvas');
  assert(!existing.hasAttribute('data-uq-family'));
  existing.querySelector('.text-2xs').textContent = 'NUMBER';
  await settings({ ...compactOnly, canvas:false });
  assert(!existing.hasAttribute('data-uq-compact'));
  assert(query('[data-uq-compact="tray"]'));
  await settings({ compact:true, enabled:false });
  assert(!query('[data-uq-compact],[data-uq-compact-identity],[data-uq-compact-type]'));
  const group = dom.window.document.createElement('div');
  group.setAttribute('aria-roledescription', 'draggable');
  group.innerHTML = card(catalog.components[0], 'temporary');
  const groupHeader = group.querySelector('.header');
  groupHeader.setAttribute('data-component-key', 'compact-group');
  groupHeader.setAttribute('data-slot', 'collapsible-trigger');
  const children = dom.window.document.createElement('div');
  children.innerHTML = card(catalog.components[0], 'compact-child');
  group.replaceChildren(groupHeader, children);
  dom.window.document.body.append(group);
  await settings(compactOnly);
  assert.equal(groupHeader.dataset.uqCompact, 'canvas');
  assert.equal(query('[data-component-key="compact-child"]').dataset.uqCompact, 'canvas');
  assert(!group.hasAttribute('data-uq-compact'));
  assert(!children.hasAttribute('data-uq-compact'));
  group.remove();
  await settings({ symbols:false, labels:false, accents:true });
  assert(!svg.hasAttribute('data-uq-symbol'));
  assert(!existing.querySelector('.text-2xs').hasAttribute('data-uq-label'));
  assert(existing.hasAttribute('data-uq-accent'));
  assert.equal(svg.innerHTML, shape);
  const trayName = dom.window.document.createElement('span');
  trayName.setAttribute('data-slot', 'tooltip-trigger');
  trayName.textContent = 'Number';
  query('[data-tray-type="number"]').append(trayName);
  await settings({ icons:false, tiles:true, trayLabels:true, labels:true });
  assert(!svg.hasAttribute('data-uq-icon'));
  assert(!svg.hasAttribute('data-uq-symbol'));
  assert(svg.parentElement.hasAttribute('data-uq-tile'));
  assert(trayName.hasAttribute('data-uq-label'));
  assert(existing.querySelector('.text-2xs').hasAttribute('data-uq-label'));
  await settings({ icons:true, tiles:false, trayLabels:false, labels:false });
  assert(svg.hasAttribute('data-uq-icon'));
  assert(!svg.parentElement.hasAttribute('data-uq-tile'));
  assert(!query('[data-uq-icon-background]'));
  assert(!trayName.hasAttribute('data-uq-label'));
  await settings({ canvas:false, tray:true, trayLabels:true });
  assert(!existing.hasAttribute('data-uq-family'));
  assert(trayName.hasAttribute('data-uq-label'));
  await settings({ enabled:false });
  assert.equal(dom.window.document.querySelectorAll('[data-uq-family],[data-uq-icon],[data-uq-label],[data-uq-symbol],[data-uq-accent],[data-uq-tile],[data-uq-icon-background]').length, 0);
  await settings({ tray:false });
  assert(!query('[data-tray-type="number"]').hasAttribute('data-uq-family'));
  assert(existing.hasAttribute('data-uq-family'));
  const extra = dom.window.document.createElement('div');
  extra.innerHTML = card(catalog.components[0], 'new-card');
  dom.window.document.body.append(extra);
  await settle();
  assert(query('[data-component-key="new-card"]').hasAttribute('data-uq-family'));
  existing.querySelector('.text-2xs').textContent = 'DECISIONS';
  await settle();
  assert.equal(existing.dataset.uqFamily, 'logic');
  existing.querySelector('.text-2xs').textContent = 'UNSUPPORTED';
  await settle();
  assert(!existing.hasAttribute('data-uq-family'));
  existing.querySelector('.text-2xs').textContent = 'NUMBER';
  await settings({});
  assert(!query('[data-uq-row-layout],[data-uq-slot],[data-uq-section],[data-uq-row-contents]'));
  await rowLayout({ ...middle, icon:'right' });
  const header = existing.querySelector('.header');
  assert(header.hasAttribute('data-uq-row-layout'));
  assert(header.querySelector('.trailing').hasAttribute('data-uq-row-contents'));
  assert.deepEqual([...header.querySelectorAll('[data-uq-section]')].map(element => element.dataset.uqSection + ':' + element.dataset.uqSlot), ['icon:right', 'name:left', 'type:middle', 'chip:middle', 'actions:right']);
  await settings({ compact:true });
  assert.equal(existing.dataset.uqCompact, 'canvas');
  assert(header.hasAttribute('data-uq-row-layout'));
  const container = dom.window.document.createElement('div');
  container.setAttribute('aria-roledescription', 'draggable');
  container.innerHTML = card(catalog.components[0], 'layout-group');
  const containerHeader = container.querySelector('.header');
  containerHeader.setAttribute('data-component-key', 'layout-group');
  containerHeader.setAttribute('data-slot', 'collapsible-trigger');
  containerHeader.querySelector('.trailing').insertAdjacentHTML('beforeend', '<span title="Unsaved changes"></span><svg class="lucide lucide-chevron-down"></svg>');
  const nested = dom.window.document.createElement('div');
  nested.innerHTML = card(catalog.components[0], 'layout-child');
  container.replaceChildren(containerHeader, nested);
  const unrecognized = dom.window.document.createElement('div');
  unrecognized.innerHTML = card(catalog.components[0], 'layout-extra');
  unrecognized.querySelector('.header').append(dom.window.document.createElement('span'));
  dom.window.document.body.append(container, unrecognized);
  await rowLayout(allLeft);
  assert(containerHeader.hasAttribute('data-uq-row-layout'));
  assert.equal(containerHeader.querySelector('[title="Unsaved changes"]').dataset.uqSection, 'chip');
  assert.equal(containerHeader.querySelector('.lucide-chevron-down').dataset.uqSection, 'chevron');
  assert(!containerHeader.querySelector('.lucide-chevron-down').hasAttribute('data-uq-slot'));
  assert(query('[data-component-key="layout-child"] .header').hasAttribute('data-uq-row-layout'));
  assert(!nested.hasAttribute('data-uq-section'));
  assert(!unrecognized.querySelector('[data-uq-row-layout],[data-uq-section]'));
  await settings({ canvas:false });
  assert(!query('[data-uq-row-layout],[data-uq-section]'));
  await settings({ enabled:false });
  assert(!query('[data-uq-row-layout],[data-uq-section]'));
  await settings({ icons:false, tiles:false, labels:false, symbols:false });
  assert(query('[data-uq-row-layout]'));
  await rowLayout({ ...allLeft, enabled:false });
  assert(!query('[data-uq-row-layout],[data-uq-slot],[data-uq-section],[data-uq-row-contents]'));
  container.remove();
  unrecognized.remove();
  await settings({});
  const holder = dom.window.document.createElement('div');
  holder.innerHTML = nestedContainers;
  dom.window.document.body.append(holder);
  await settle();
  assert(!holder.querySelector('[data-uq-container]'));
  await settings(allContainers);
  assert.equal(query('#outer-frame').dataset.uqFamily, 'layout');
  assert.equal(query('#inner-frame').dataset.uqFamily, 'layout');
  assert(query('#custom-frame').hasAttribute('data-uq-container'));
  assert(!query('#custom-frame').hasAttribute('data-uq-family'));
  assert(query('#outer-wrap').hasAttribute('data-uq-container-spacing'));
  assert(query('#inner-body').hasAttribute('data-uq-container-body-spacing'));
  assert(query('#inner-body').hasAttribute('data-uq-container-guide'));
  assert(query('[data-component-key="outer"]').hasAttribute('data-uq-container-header'));
  assert.deepEqual(['outer', 'inner', 'custom'].map(key => query(`[data-component-key="${key}"]`).dataset.uqDepth), ['0', '1', '1']);
  assert.deepEqual(['outer', 'inner'].map(key => query(`#${key}-body`).dataset.uqContainerShade), ['0', '1']);
  assert.equal(query('#inner-body').dataset.uqContainerEnd, 'inner');
  assert(!query('[data-component-key="inner-leaf"]').hasAttribute('data-uq-container'));
  assert(![...query('#context-trigger').attributes, ...query('#context-body').attributes].some(attribute => attribute.name.startsWith('data-uq')));
  query('#inner-frame [data-slot="collapsible-content"]').remove();
  query('[data-component-key="inner"]').removeAttribute('data-panel-open');
  await settle();
  assert(query('[data-component-key="inner"]').hasAttribute('data-uq-container-sticky'));
  await settings({ containerGuides:true });
  assert(query('#outer-body').hasAttribute('data-uq-container-guide'));
  assert(!query('[data-uq-container-spacing],[data-uq-container-body-spacing],[data-uq-container-header],[data-uq-container-sticky],[data-uq-depth],[data-uq-container-shade],[data-uq-container-end]'));
  await settings({ containerGuides:true, canvas:false });
  assert(!query('[data-uq-container],[data-uq-container-guide]'));
  holder.remove();
  await settings({});
  // The By Type and alphabetical views list flat rows with an "in parent • Type" details line.
  const listRow = (key, details) => `<button data-component-key="${key}"><div class="tile">${icon}</div><div class="flex-1 min-w-0"><div class="text-sm">${key}</div><div class="text-muted-foreground text-xs">${details}</div></div></button>`;
  const list = dom.window.document.createElement('div');
  list.innerHTML = listRow('listButton', '<span>in fgHeader</span><span>•</span><span>Button</span>') + listRow('listPlugin', '<span>in panel</span><span>•</span><span>Plugin</span>') + listRow('listRoot', '<span>Decisions</span>') + listRow('listModule', '<span>in panel</span><span>•</span><span>Module 6552482f</span>') + listRow('listParent', '<span>in Hidden</span>');
  dom.window.document.body.append(list);
  await settle();
  assert.deepEqual(['listButton', 'listPlugin', 'listRoot'].map(key => query(`[data-component-key="${key}"]`).dataset.uqFamily), ['actions', 'integrations', 'logic']);
  assert(query('[data-component-key="listButton"] .text-xs > :last-child').hasAttribute('data-uq-label'));
  assert(query('[data-component-key="listButton"] .tile').hasAttribute('data-uq-tile'));
  assert(!query('[data-component-key="listModule"]').hasAttribute('data-uq-family'));
  assert(!query('[data-component-key="listParent"]').hasAttribute('data-uq-family'));
  await settings({ compact:true });
  await rowLayout(allLeft);
  assert(!list.querySelector('[data-uq-compact],[data-uq-row-layout]'));
  await rowLayout({ ...allLeft, enabled:false });
  list.remove();
  await settings({});
  // UI blocks carry a per-environment ID and match by name; custom components (BYOC) share one group,
  // including one named like a built-in, and show a package icon on the canvas.
  const packageIcon = '<svg class="lucide lucide-package" viewBox="0 0 24 24"></svg>';
  const extras = dom.window.document.createElement('div');
  extras.innerHTML = '<div data-tray-type="uiBlock::6abe616e836eb2cfdd35162d" aria-label="Simple Grid component">' + icon + '<span>Simple Grid</span></div>'
    + '<div data-tray-type="uiBlock::0123" aria-label="Team Header component">' + icon + '<span>Team Header</span></div>'
    + '<div data-tray-type="byoc::smartPagination" aria-label="Smart Pagination component">' + icon + '<span>Smart Pagination</span></div>'
    + '<div data-tray-type="byoc::SimpleGrid" aria-label="Simple Grid component">' + icon + '<span>Simple Grid</span></div>'
    + '<div data-component-key="customComponent"><div class="header"><div class="tile">' + packageIcon + '</div><div><strong>customComponent</strong><div class="text-2xs">SMARTPAGINATION</div></div></div></div>'
    + '<div data-component-key="customGrid"><div class="header"><div class="tile">' + packageIcon + '</div><div><strong>customGrid</strong><div class="text-2xs">SIMPLEGRID</div></div></div></div>';
  dom.window.document.body.append(extras);
  await settle();
  assert.deepEqual([...extras.children].map(element => element.dataset.uqFamily || null), ['grids', null, 'custom', 'custom', 'custom', 'custom']);
  assert.equal(query('[data-component-key="customComponent"] svg').dataset.uqSymbol, 'custom');
  extras.remove();
  await settle();
  // With full backgrounds the dependency chip takes the row's colors instead of Unqork's brand tint.
  const chip = query('[data-component-key="number"] [data-slot="popover-trigger"]');
  assert(!chip.hasAttribute('data-uq-chip'));
  await settings({ backgrounds:true });
  assert(chip.hasAttribute('data-uq-chip'));
  const styledChips = [...dom.window.document.querySelectorAll('[data-component-key][data-uq-family] [data-slot="popover-trigger"]')].filter(element => element.closest('[data-component-key]').hasAttribute('data-uq-family'));
  assert.deepEqual([...dom.window.document.querySelectorAll('[data-uq-chip]')], styledChips, 'Every styled canvas row, including nested ones');
  assert(styledChips.length > catalog.components.length);
  // The row's own actions menu follows its colors too; a nested row's menu belongs to that row.
  const menu = query('[data-component-key="number"] [data-slot="dropdown-menu-trigger"]');
  assert(menu.hasAttribute('data-uq-row-control'));
  assert.equal(dom.window.document.querySelectorAll('[data-uq-row-control]').length, styledChips.length);
  await settings({});
  assert(!dom.window.document.querySelector('[data-uq-chip],[data-uq-row-control]'));
  // Tinted container headers are colored surfaces too, so their own controls follow; plain rows keep Unqork's.
  const headerHolder = dom.window.document.createElement('div');
  headerHolder.innerHTML = nestedContainers;
  dom.window.document.body.append(headerHolder);
  await settings({ containerHeaders:true });
  assert(query('[data-component-key="outer"] [data-slot="dropdown-menu-trigger"]').hasAttribute('data-uq-row-control'));
  assert(!query('[data-component-key="custom"] [data-slot="dropdown-menu-trigger"]').hasAttribute('data-uq-row-control'), 'Unrecognized containers have no group colors');
  assert(!menu.hasAttribute('data-uq-row-control'));
  headerHolder.remove();
  await settings({});
  // Group colors and shapes come from the palette through root variables, so every group and
  // shape in content.css has a value, and a picked color reaches icons, backgrounds and shapes.
  const root = dom.window.document.documentElement.style;
  const colors = require('./lib.cjs').load('component-colors');
  const cssFamilies = [...new Set([...css.matchAll(/\[data-uq-family="(\w+)"\] \{ --uq-ink:var/g)].map(match => match[1]))];
  assert.deepEqual(cssFamilies, Array.from(colors.families, family => family.id));
  const cssSymbols = [...css.matchAll(/^\[data-uq-symbol="([^"]+)"\] \{ --uq-symbol:var/gm)].map(match => match[1]);
  assert(cssSymbols.length >= 12);
  for (const type of cssSymbols) {
    assert.match(root.getPropertyValue('--uq-symbol-' + type), /^url\("data:image\/svg\+xml,/, type + ' has a shape');
    assert(root.getPropertyValue('--uq-symbol-' + type + '-dark'), type + ' has a dark shape');
  }
  assert.equal(root.getPropertyValue('--uq-grids-ink'), '#155E75');
  assert.equal(root.getPropertyValue('--uq-grids-dark-tint'), '#164E63');
  assert(decodeURIComponent(root.getPropertyValue('--uq-symbol-datagrid')).includes('stroke="#155E75"'));
  // Light and dark are picked separately; a theme with one picked color derives its partner.
  change({ componentColors:{ newValue:{ grids:{ light:{ ink:'#0ea5e9', tint:'#fef3c7' }, dark:{ tint:'#7f1d1d' } }, inputs:{ light:{ ink:'not a color' } } } } }, 'local');
  assert.equal(root.getPropertyValue('--uq-grids-ink'), '#0EA5E9');
  assert.equal(root.getPropertyValue('--uq-grids-tint'), '#FEF3C7', 'Both picked colors are used exactly');
  assert.equal(root.getPropertyValue('--uq-grids-dark-tint'), '#7F1D1D');
  const derivedInk = colors.partner('dark', 'tint', '#7F1D1D');
  assert.equal(root.getPropertyValue('--uq-grids-dark-ink'), derivedInk);
  assert(colors.contrast(derivedInk, '#7F1D1D') >= 5, 'A derived text color stays readable');
  assert(decodeURIComponent(root.getPropertyValue('--uq-symbol-datagrid')).includes('stroke="#0EA5E9"'));
  assert(decodeURIComponent(root.getPropertyValue('--uq-symbol-datagrid-dark')).includes('stroke="' + derivedInk + '"'));
  assert.equal(root.getPropertyValue('--uq-inputs-ink'), '#1E40AF', 'Invalid colors keep the default');
  assert.equal(root.getPropertyValue('--uq-layout-dark-ink'), '#C4B5FD', 'Other groups keep their defaults');
  change({ componentColors:{ newValue:undefined } }, 'local');
  assert.equal(root.getPropertyValue('--uq-grids-ink'), '#155E75');
  // Changes away from components, such as streaming Build Agent text, never trigger a pass.
  const unrelated = dom.window.document.createElement('div');
  dom.window.document.body.append(unrelated);
  await settle();
  const frameRequest = dom.window.requestAnimationFrame;
  let passes = 0;
  dom.window.requestAnimationFrame = callback => { passes++; return frameRequest(callback); };
  for (let i = 0; i < 5; i++) { unrelated.textContent = 'reply ' + i; unrelated.className = 'streaming-' + i; await settle(); }
  assert.equal(passes, 0, 'Unrelated changes are ignored');
  query('[data-component-key="number"] .text-2xs').textContent = 'DECISIONS';
  await settle();
  assert.equal(passes, 1, 'A changed component still gets a pass');
  assert.equal(query('[data-component-key="number"]').dataset.uqFamily, 'logic');
  query('[data-component-key="number"] .text-2xs').textContent = 'NUMBER';
  await settle();
  dom.window.requestAnimationFrame = frameRequest;
  unrelated.remove();
  dom.window.history.pushState({}, '', '/ide/other');
  dom.window.document.body.append(dom.window.document.createElement('div'));
  await settle();
  assert.equal(dom.window.document.querySelectorAll('[data-uq-family]').length, 0);
  testObserver.disconnect();
  dom.window.close();
  console.log('PASS: all 54 types, UI blocks, custom components, shape colors, aliases, nested ownership, row layout placement, container structure and depth, unknown types, dynamic inserts/type changes, scope, disable cleanup, SVG preservation and click handlers.');
  const browser = await (firefoxMode ? firefox : chromium).launch({ ...(firefoxMode ? {} : process.env.CHROME_PATH ? { executablePath:process.env.CHROME_PATH } : {}), headless:true });
  const page = await browser.newPage({ viewport:{ width:1100, height:820 } });
  const failures = [];
  page.on('pageerror', error => failures.push(error.message));
  await page.route('https://american-equity-staging.unqork.io/**', route => route.fulfill({ contentType:'text/html', body:'<meta charset="utf-8">'+fixture }));
  await page.goto('https://american-equity-staging.unqork.io/ide/builder/test');
  await page.evaluate((useFirefox) => { window[useFirefox ? 'browser' : 'chrome'] = { storage: { local: { get:async () => ({}) }, onChanged: { addListener: listener => { window.updateAppearance = listener; } } } }; }, firefoxMode);
  await page.addStyleTag({ content:'body{font:14px Segoe UI;background:#f8fafc;color:#172033;margin:28px}main{display:grid;grid-template-columns:260px 1fr;gap:32px}aside,section{display:grid;align-content:start;gap:10px}[data-tray-type]{display:flex;align-items:center;gap:12px;border:1px solid #d9e1ec;border-radius:6px;padding:8px}[data-handle]{width:10px;height:12px}section>[data-component-key]{border:1px solid #d9e1ec;border-radius:8px;padding:12px}.header{display:flex;align-items:center;gap:12px}.tile{width:32px;height:32px;display:grid;place-items:center;border-radius:6px}.text-2xs{font-size:10px;margin-top:4px}.trailing{margin-left:auto;display:flex;align-items:center;gap:4px}.header button{border:0;background:none;color:inherit}.dark body{background:#0b0e13;color:#cbd2da}.dark [data-component-key],.dark [data-tray-type]{border-color:#262d38}main>* > :nth-child(n+12){display:none}' });
  await page.addStyleTag({ content:css });
  await page.addScriptTag({ content:script });
  // The accent must keep Unqork's selection ring, a Tailwind box-shadow layer on the same row.
  assert.match(await page.evaluate(() => {
    const row = document.createElement('div');
    row.setAttribute('data-uq-accent', '');
    row.setAttribute('data-uq-family', 'inputs');
    row.style.setProperty('--tw-ring-shadow', '0 0 0 2px rgb(0, 188, 200)');
    document.body.append(row);
    const shadow = getComputedStyle(row).boxShadow;
    row.remove();
    return shadow;
  }), /inset.*rgb\(0, 188, 200\) 0px 0px 0px 2px/);
  await page.waitForSelector('[data-uq-family]');
  assert.equal(await page.locator('[data-tray-type="number"] svg').first().evaluate(element => getComputedStyle(element).color), 'rgb(30, 64, 175)');
  await page.screenshot({ path:path.join(__dirname, '../artifacts/extension-light.png') });
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  assert.equal(await page.locator('[data-tray-type="number"] svg').first().evaluate(element => getComputedStyle(element).color), 'rgb(147, 197, 253)');
  const custom = page.locator('[data-tray-type="select"] svg').first();
  assert.match(await custom.evaluate(element => getComputedStyle(element).backgroundImage), /data:image\/svg\+xml/);
  assert.equal(await custom.locator('path').evaluate(element => getComputedStyle(element).visibility), 'hidden');
  await page.screenshot({ path:path.join(__dirname, '../artifacts/extension-dark.png') });
  const regularHeight = await page.locator('[data-component-key="number"]').evaluate(el => el.getBoundingClientRect().height);
  await page.evaluate(() => window.updateAppearance({ appearance:{ newValue:{ compact:true } } }, 'local'));
  await page.waitForSelector('[data-uq-compact="canvas"]');
  assert(await page.locator('[data-component-key="number"]').evaluate(el => el.getBoundingClientRect().height) < regularHeight);
  await page.screenshot({ path:path.join(__dirname, '../artifacts/compact-dark.png') });
  await page.evaluate(() => document.documentElement.classList.remove('dark'));
  await page.screenshot({ path:path.join(__dirname, '../artifacts/compact-light.png') });
  await page.setViewportSize({ width:640, height:820 });
  assert(await page.locator('[data-component-key="number"] [data-slot="dropdown-menu-trigger"]').isVisible());
  assert.equal(await page.locator('[data-component-key="number"] .text-2xs').evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await page.evaluate(() => window.updateAppearance({ appearance:{ newValue:{} } }, 'local'));
  await page.waitForFunction(() => !document.querySelector('[data-uq-compact]'));
  await page.setViewportSize({ width:1100, height:820 });
  const row = page.locator('[data-component-key="number"]');
  const boxes = () => row.evaluate(card => Object.fromEntries(['.header', '.tile', 'strong', '.text-2xs', '[data-slot="popover-trigger"]', '[data-slot="dropdown-menu-trigger"]'].map(selector => [selector, card.querySelector(selector).getBoundingClientRect().toJSON()])));
  const native = await boxes();
  const place = value => page.evaluate(value => window.updateAppearance({ rowLayout:{ newValue:value } }, 'local'), value);
  await place(allLeft);
  await page.waitForSelector('[data-uq-row-layout]');
  let current = await boxes();
  assert.equal(await row.locator('[data-slot="dropdown-menu-trigger"]').evaluate(element => getComputedStyle(element).order), '15');
  assert(current['.text-2xs'].left > current.strong.right && current['.text-2xs'].left - current.strong.right < 20);
  assert(current['[data-slot="dropdown-menu-trigger"]'].right < current['.header'].right - 200);
  await page.screenshot({ path:path.join(__dirname, '../artifacts/row-layout-left.png') });
  await place(middle);
  await page.waitForFunction(() => getComputedStyle(document.querySelector('[data-component-key="number"] .text-2xs')).order === '33');
  current = await boxes();
  // The middle group sits halfway between the left and right groups.
  const gap = (current['.text-2xs'].left + current['[data-slot="popover-trigger"]'].right) / 2 - (current.strong.right + current['[data-slot="dropdown-menu-trigger"]'].left) / 2;
  assert(current['.text-2xs'].left > current.strong.right + 100 && Math.abs(gap) < 12);
  assert(Math.abs(current['[data-slot="dropdown-menu-trigger"]'].right - native['[data-slot="dropdown-menu-trigger"]'].right) < 2);
  await page.screenshot({ path:path.join(__dirname, '../artifacts/row-layout-middle.png') });
  await page.setViewportSize({ width:640, height:820 });
  assert(await row.locator('[data-slot="dropdown-menu-trigger"]').isVisible());
  // A Columns cell clips its contents without scrolling, so its containers must not pin.
  await page.evaluate(html => document.body.insertAdjacentHTML('beforeend', `<div id="containers">${html}</div>`), nestedContainers + `<div style="overflow:hidden">${containerFrame('PANEL', 'cell', '')}</div>`);
  await page.evaluate(value => window.updateAppearance({ appearance:{ newValue:value } }, 'local'), allContainers);
  await page.waitForSelector('[data-uq-container-sticky]');
  const sticky = key => page.locator(`[data-component-key="${key}"]`).evaluate(element => { const style = getComputedStyle(element); return [style.position, style.top]; });
  assert.deepEqual(await sticky('outer'), ['sticky', '0px']);
  assert.deepEqual(await sticky('inner'), ['sticky', '56px']);
  assert.equal((await sticky('cell'))[0], 'static');
  // Unqork selects a container from its identity block and toggles it from the rest of the header.
  assert(await page.locator('[data-component-key="outer"]').evaluate(header => {
    header.scrollIntoView({ block:'center' });
    const box = header.getBoundingClientRect(), name = header.querySelector('strong').getBoundingClientRect();
    const target = document.elementFromPoint(name.right + 30, box.top + box.height / 2);
    window.scrollTo(0, 0);
    return target === header.querySelector('[data-uq-row-contents="identity"]');
  }));
  assert.match(await page.locator('[data-component-key="outer"]').evaluate(element => getComputedStyle(element).backgroundImage), /gradient/);
  assert.match(await page.locator('#inner-body').evaluate(element => getComputedStyle(element, '::after').content), /End of\W*inner/);
  assert.notEqual(await page.locator('#inner-body').evaluate(element => getComputedStyle(element).borderLeftWidth), '0px');
  await page.evaluate(value => window.updateAppearance({ appearance:{ newValue:value } }, 'local'), { ...allContainers, compact:true });
  await page.waitForSelector('[data-component-key="inner"][data-uq-compact]');
  assert.deepEqual(await sticky('inner'), ['sticky', '38px']);
  await page.screenshot({ path:path.join(__dirname, '../artifacts/containers.png') });
  await page.evaluate(() => { document.getElementById('containers').remove(); window.updateAppearance({ appearance:{ newValue:{} } }, 'local'); });
  await page.setViewportSize({ width:1100, height:820 });
  await place({ ...middle, enabled:false });
  await page.waitForFunction(() => !document.querySelector('[data-uq-row-layout],[data-uq-section]'));
  assert.deepEqual(await boxes(), native);
  await page.emulateMedia({ forcedColors:'active' });
  assert.equal(await custom.evaluate(element => getComputedStyle(element).backgroundImage), 'none');
  assert.equal(await custom.locator('path').evaluate(element => getComputedStyle(element).visibility), 'visible');
  assert.deepEqual(failures, []);
  await browser.close();
  console.log('PASS: browser rendering, light/dark colors, custom glyph overlays, forced-colors fallback, no page errors.');
})().catch(error => { console.error(error); process.exitCode = 1; });
