const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const { chromium, firefox } = require('playwright');
const firefoxMode = process.argv.includes('--firefox');
fs.mkdirSync(path.resolve(__dirname, '../artifacts'), { recursive:true });
const root = path.resolve(__dirname, '../dist', firefoxMode ? 'firefox' : 'chrome');
const catalog = JSON.parse(fs.readFileSync(path.join(__dirname, '../docs/component-catalog.json'), 'utf8'));
const script = fs.readFileSync(path.join(root, 'content.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'content.css'), 'utf8');
const icon = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 9v12"/></svg>';
const tray = component => `<div data-tray-type="${component.type}" role="button" tabindex="0">${icon}<span>${component.label}</span><svg data-handle="true"></svg></div>`;
const card = (component, key = component.type) => `<div data-component-key="${key}" role="button" tabindex="0"><div class="header"><div class="tile">${icon}</div><div><strong>${component.label} example</strong><div class="text-2xs">${component.label === 'Plug-In' ? 'PLUGIN' : component.label.toUpperCase()}</div></div><button aria-label="Actions">⋮</button></div></div>`;
const fixture = `<main><aside>${catalog.components.map(tray).join('')}</aside><section>${catalog.components.map(component => card(component)).join('')}<div data-component-key="unknown">${icon}<div class="text-2xs">UNKNOWN TYPE</div></div><div data-component-key="imported"><a>Module: Example</a>${card(catalog.components[0], 'nested-child')}</div></section></main>`;
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
assert.deepEqual(manifest.permissions, ['storage', 'activeTab', 'scripting']);
for (const file of [...manifest.content_scripts[0].js, ...manifest.content_scripts[0].css, manifest.action.default_popup]) assert(fs.existsSync(path.join(root, file)));
const dom = new JSDOM(fixture, { url:'https://american-equity-staging.unqork.io/ide/builder/test', runScripts:'outside-only', pretendToBeVisual:true });
let change;
let testObserver;
const NativeObserver = dom.window.MutationObserver;
dom.window.MutationObserver = class extends NativeObserver {
  constructor(callback) { super(callback); testObserver = this; }
};
dom.window[firefoxMode ? 'browser' : 'chrome'] = { storage: { local: { get:async () => ({}) }, onChanged: { addListener: listener => { change = listener; } } } };
const settle = () => new Promise(resolve => setTimeout(resolve, 70));
const query = selector => dom.window.document.querySelector(selector);
async function settings(value) { change({ appearance: { newValue:value } }, 'local'); await settle(); }
(async () => {
  dom.window.eval(script);
  await settle();
  assert.equal(dom.window.document.querySelectorAll('[data-uq-family]').length, 105);
  assert.equal(query('[data-tray-type="integrator"]').dataset.uqFamily, 'integrations');
  assert.equal(query('[data-component-key="integrator"]').dataset.uqFamily, 'integrations');
  assert(!query('[data-component-key="unknown"]').hasAttribute('data-uq-family'));
  assert(!query('[data-component-key="imported"]').hasAttribute('data-uq-family'));
  assert(!query('[data-handle]').hasAttribute('data-uq-icon'));
  const existing = query('[data-component-key="number"]');
  const svg = existing.querySelector('svg');
  const shape = svg.innerHTML;
  let clicked = false;
  existing.addEventListener('click', () => { clicked = true; });
  existing.click();
  assert(clicked);
  assert(!query('[data-uq-compact]'));
  const compactOnly = { compact:true, icons:false, tiles:false, labels:false, symbols:false };
  await settings(compactOnly);
  assert.equal(existing.dataset.uqCompact, 'canvas');
  assert.equal(query('[data-tray-type="number"]').dataset.uqCompact, 'tray');
  assert(!query('[data-component-key="imported"]').hasAttribute('data-uq-compact'));
  assert(!svg.hasAttribute('data-uq-icon'));
  existing.querySelector('.text-2xs').textContent = 'CUSTOM TYPE';
  await settle();
  assert.equal(existing.dataset.uqCompact, 'canvas');
  assert(!existing.hasAttribute('data-uq-family'));
  existing.querySelector('.text-2xs').textContent = 'NUMBER';
  await settings({ ...compactOnly, canvas:false });
  assert(!existing.hasAttribute('data-uq-compact'));
  assert(query('[data-uq-compact="tray"]'));
  await settings({ compact:true, enabled:false });
  assert(!query('[data-uq-compact],[data-uq-compact-identity],[data-uq-compact-type]'));
  const group = dom.window.document.createElement('div');
  group.setAttribute('aria-roledescription', 'draggable');
  group.innerHTML = card(catalog.components[0], 'temporary');
  const groupHeader = group.querySelector('.header');
  groupHeader.setAttribute('data-component-key', 'compact-group');
  groupHeader.setAttribute('data-slot', 'collapsible-trigger');
  const children = dom.window.document.createElement('div');
  children.innerHTML = card(catalog.components[0], 'compact-child');
  group.replaceChildren(groupHeader, children);
  dom.window.document.body.append(group);
  await settings(compactOnly);
  assert.equal(groupHeader.dataset.uqCompact, 'canvas');
  assert.equal(query('[data-component-key="compact-child"]').dataset.uqCompact, 'canvas');
  assert(!group.hasAttribute('data-uq-compact'));
  assert(!children.hasAttribute('data-uq-compact'));
  group.remove();
  await settings({ symbols:false, labels:false, accents:true });
  assert(!svg.hasAttribute('data-uq-symbol'));
  assert(!existing.querySelector('.text-2xs').hasAttribute('data-uq-label'));
  assert(existing.hasAttribute('data-uq-accent'));
  assert.equal(svg.innerHTML, shape);
  const trayName = dom.window.document.createElement('span');
  trayName.setAttribute('data-slot', 'tooltip-trigger');
  trayName.textContent = 'Number';
  query('[data-tray-type="number"]').append(trayName);
  await settings({ icons:false, tiles:true, trayLabels:true, labels:true });
  assert(!svg.hasAttribute('data-uq-icon'));
  assert(!svg.hasAttribute('data-uq-symbol'));
  assert(svg.parentElement.hasAttribute('data-uq-tile'));
  assert(trayName.hasAttribute('data-uq-label'));
  assert(existing.querySelector('.text-2xs').hasAttribute('data-uq-label'));
  await settings({ icons:true, tiles:false, trayLabels:false, labels:false });
  assert(svg.hasAttribute('data-uq-icon'));
  assert(!svg.parentElement.hasAttribute('data-uq-tile'));
  assert(!query('[data-uq-icon-background]'));
  assert(!trayName.hasAttribute('data-uq-label'));
  await settings({ canvas:false, tray:true, trayLabels:true });
  assert(!existing.hasAttribute('data-uq-family'));
  assert(trayName.hasAttribute('data-uq-label'));
  await settings({ enabled:false });
  assert.equal(dom.window.document.querySelectorAll('[data-uq-family],[data-uq-icon],[data-uq-label],[data-uq-symbol],[data-uq-accent],[data-uq-tile],[data-uq-icon-background]').length, 0);
  await settings({ tray:false });
  assert(!query('[data-tray-type="number"]').hasAttribute('data-uq-family'));
  assert(existing.hasAttribute('data-uq-family'));
  const extra = dom.window.document.createElement('div');
  extra.innerHTML = card(catalog.components[0], 'new-card');
  dom.window.document.body.append(extra);
  await settle();
  assert(query('[data-component-key="new-card"]').hasAttribute('data-uq-family'));
  existing.querySelector('.text-2xs').textContent = 'DECISIONS';
  await settle();
  assert.equal(existing.dataset.uqFamily, 'decisions');
  existing.querySelector('.text-2xs').textContent = 'UNSUPPORTED';
  await settle();
  assert(!existing.hasAttribute('data-uq-family'));
  dom.window.history.pushState({}, '', '/ide/other');
  dom.window.document.body.append(dom.window.document.createElement('div'));
  await settle();
  assert.equal(dom.window.document.querySelectorAll('[data-uq-family]').length, 0);
  testObserver.disconnect();
  dom.window.close();
  console.log('PASS: all 52 types, aliases, nested ownership, unknown types, dynamic inserts/type changes, scope, disable cleanup, SVG preservation and click handlers.');
  const browser = await (firefoxMode ? firefox : chromium).launch({ ...(firefoxMode ? {} : process.env.CHROME_PATH ? { executablePath:process.env.CHROME_PATH } : {}), headless:true });
  const page = await browser.newPage({ viewport:{ width:1100, height:820 } });
  const failures = [];
  page.on('pageerror', error => failures.push(error.message));
  await page.route('https://american-equity-staging.unqork.io/**', route => route.fulfill({ contentType:'text/html', body:'<meta charset="utf-8">'+fixture }));
  await page.goto('https://american-equity-staging.unqork.io/ide/builder/test');
  await page.evaluate((useFirefox) => { window[useFirefox ? 'browser' : 'chrome'] = { storage: { local: { get:async () => ({}) }, onChanged: { addListener: listener => { window.updateAppearance = listener; } } } }; }, firefoxMode);
  await page.addStyleTag({ content:'body{font:14px Segoe UI;background:#f8fafc;color:#172033;margin:28px}main{display:grid;grid-template-columns:260px 1fr;gap:32px}aside,section{display:grid;align-content:start;gap:10px}[data-tray-type]{display:flex;align-items:center;gap:12px;border:1px solid #d9e1ec;border-radius:6px;padding:8px}[data-handle]{width:10px;height:12px}section>[data-component-key]{border:1px solid #d9e1ec;border-radius:8px;padding:12px}.header{display:flex;align-items:center;gap:12px}.tile{width:32px;height:32px;display:grid;place-items:center;border-radius:6px}.text-2xs{font-size:10px;margin-top:4px}.header button{margin-left:auto;border:0;background:none;color:inherit}.dark body{background:#0b0e13;color:#cbd2da}.dark [data-component-key],.dark [data-tray-type]{border-color:#262d38}main>* > :nth-child(n+12){display:none}' });
  await page.addStyleTag({ content:css });
  await page.addScriptTag({ content:script });
  await page.waitForSelector('[data-uq-family]');
  assert.equal(await page.locator('[data-tray-type="number"] svg').first().evaluate(element => getComputedStyle(element).color), 'rgb(29, 78, 216)');
  await page.screenshot({ path:path.join(__dirname, '../artifacts/extension-light.png') });
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  assert.equal(await page.locator('[data-tray-type="number"] svg').first().evaluate(element => getComputedStyle(element).color), 'rgb(147, 197, 253)');
  const custom = page.locator('[data-tray-type="select"] svg').first();
  assert.match(await custom.evaluate(element => getComputedStyle(element).backgroundImage), /data:image\/svg\+xml/);
  assert.equal(await custom.locator('path').evaluate(element => getComputedStyle(element).visibility), 'hidden');
  await page.screenshot({ path:path.join(__dirname, '../artifacts/extension-dark.png') });
  const regularHeight = await page.locator('[data-component-key="number"]').evaluate(el => el.getBoundingClientRect().height);
  await page.evaluate(() => window.updateAppearance({ appearance:{ newValue:{ compact:true } } }, 'local'));
  await page.waitForSelector('[data-uq-compact="canvas"]');
  assert(await page.locator('[data-component-key="number"]').evaluate(el => el.getBoundingClientRect().height) < regularHeight);
  await page.screenshot({ path:path.join(__dirname, '../artifacts/compact-dark.png') });
  await page.evaluate(() => document.documentElement.classList.remove('dark'));
  await page.screenshot({ path:path.join(__dirname, '../artifacts/compact-light.png') });
  await page.setViewportSize({ width:640, height:820 });
  assert(await page.locator('[data-component-key="number"] button').isVisible());
  assert.equal(await page.locator('[data-component-key="number"] .text-2xs').evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await page.evaluate(() => window.updateAppearance({ appearance:{ newValue:{} } }, 'local'));
  await page.waitForFunction(() => !document.querySelector('[data-uq-compact]'));
  await page.emulateMedia({ forcedColors:'active' });
  assert.equal(await custom.evaluate(element => getComputedStyle(element).backgroundImage), 'none');
  assert.equal(await custom.locator('path').evaluate(element => getComputedStyle(element).visibility), 'visible');
  assert.deepEqual(failures, []);
  await browser.close();
  console.log('PASS: browser rendering, light/dark colors, custom glyph overlays, forced-colors fallback, no page errors.');
})().catch(error => { console.error(error); process.exitCode = 1; });
