const { chromium } = require('playwright');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const lib = require('./lib.cjs');
(async () => {
  fs.mkdirSync(path.resolve(__dirname, '../artifacts'), { recursive:true });
  const extension = path.resolve(__dirname, '../dist/chrome');
  const context = await chromium.launchPersistentContext(fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'unqlock-chrome-')), {
    ...(process.env.CHROME_PATH ? { executablePath:process.env.CHROME_PATH } : { channel:'chromium' }), headless:true,
    args:[`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
    viewport:{width:420,height:740}
  });
  try {
    const page = await context.newPage();
    await page.goto('chrome://extensions');
    const extensions = await page.evaluate(() => new Promise(resolve => chrome.developerPrivate.getExtensionsInfo({}, resolve)));
    const installed = extensions.find(item => item.name === 'Unqlock');
    assert(installed, 'Unpacked extension loaded');
    assert.equal(installed.manifestErrors.length, 0);
    const builder = await context.newPage();
    await builder.route('https://another-tenant.unqork.io/**', route => route.fulfill({contentType:'text/html',body:'<html class="dark"><body><div data-tray-type="number"><svg viewBox="0 0 24 24"><path d="M3 9h18"/></svg>Number</div></body></html>'}));
    await builder.goto('https://another-tenant.unqork.io/ide/builder/test');
    await builder.waitForSelector('[data-uq-family="inputs"]');
    assert.equal(await builder.locator('svg').evaluate(element => getComputedStyle(element).color),'rgb(147, 197, 253)');
    const home = page.locator('#home');
    const status = text => page.waitForFunction(text => document.getElementById('style-status').textContent === text, text);
    const isFocused = selector => page.locator(selector).evaluate(element => element === document.activeElement);
    const openPage = async id => {
      await page.locator('#open-' + id).click();
      assert.equal(await isFocused('#' + id + '-page .page-title'), true, id + ' title receives focus');
    };
    const goHome = async id => {
      await page.locator('.page:not([hidden]) .page-back').click();
      assert.equal(await home.isVisible(), true);
      assert.equal(await isFocused('#open-' + id), true, id + ' entry regains focus');
    };
    const reopen = async () => { await page.reload(); await status('Ready'); };
    const styling = home.locator('input[data-appearance="enabled"]');
    const homeCompact = home.locator('input[data-appearance="compact"]');
    const layoutCompact = page.locator('#layout-page').getByLabel('Compact components', {exact:true});
    await page.goto(`chrome-extension://${installed.id}/popup.html`);
    await status('Ready');
    assert.match(await page.locator('#environment-summary').innerText(), /Open an Unqork page/);
    assert.equal(await page.locator('#version').textContent(), 'v' + require('../package.json').version, 'The header shows the packaged version');
    await builder.waitForSelector('#unqlock-environment');
    assert.equal(await builder.locator('#unqlock-environment span').isVisible(), false);
    // Floating launcher owns the badge label; Environments owns the groups.
    await openPage('launcher');
    await page.getByLabel('Show environment in badge', {exact:true}).check();
    await goHome('launcher');
    await openPage('environment');
    assert.equal(await page.locator('#environment-form [name="badge"]').count(), 0);
    await page.getByLabel('Group name', {exact:true}).fill('Test organization');
    await page.getByRole('textbox', {name:'Hostname', exact:true}).fill('another-tenant.unqork.io');
    await page.getByLabel('Environment for hostname', {exact:true}).selectOption('production');
    await page.getByRole('button', {name:'Add domain', exact:true}).click();
    await page.getByRole('textbox', {name:'Hostname', exact:true}).nth(1).fill('example-qa.unqork.io');
    await page.getByLabel('Environment for hostname', {exact:true}).nth(1).selectOption('qa');
    await builder.waitForFunction(() => document.querySelector('#unqlock-environment').shadowRoot.querySelector('button').dataset.kind === 'production');
    await page.screenshot({path:path.resolve(__dirname, '../artifacts/environment-settings.png'), fullPage:true});
    await builder.screenshot({path:path.resolve(__dirname, '../artifacts/environment-badge.png')});
    await page.keyboard.press('Escape');
    assert.equal(await isFocused('#open-environment'), true);
    await openPage('launcher');
    assert.equal(await page.getByLabel('Show environment in badge', {exact:true}).isChecked(), true);
    await page.getByLabel('Show environment in badge', {exact:true}).uncheck();
    await builder.waitForFunction(() => document.querySelector('#unqlock-environment').shadowRoot.querySelector('span').hidden);
    await page.getByLabel('Show environment in badge', {exact:true}).check();
    await builder.waitForFunction(() => !document.querySelector('#unqlock-environment').shadowRoot.querySelector('span').hidden);
    await page.getByLabel('Show floating launcher', {exact:true}).uncheck();
    await page.waitForSelector('.disabled-explanation.has-reason:has([name="badge"])');
    await page.getByLabel('Show floating launcher', {exact:true}).check();
    await builder.waitForSelector('#unqlock-environment');
    await goHome('launcher');
    for (const scheme of ['light', 'dark']) {
      await page.emulateMedia({colorScheme:scheme});
      await page.screenshot({path:path.resolve(__dirname, `../artifacts/menu-${scheme}.png`), fullPage:true});
      for (const id of ['style', 'layout', 'panels', 'quick', 'environment', 'launcher']) {
        await page.locator('#open-' + id).click();
        await page.screenshot({path:path.resolve(__dirname, `../artifacts/page-${id}-${scheme}.png`), fullPage:true});
        await page.keyboard.press('Escape');
        assert.equal(await isFocused('#open-' + id), true, id + ' entry regains focus after Escape');
      }
    }
    await page.emulateMedia({colorScheme:'light'});
    // Home switches and page controls are bound to the same preferences.
    assert.equal(await homeCompact.isChecked(), false);
    await homeCompact.check();
    await builder.waitForSelector('[data-uq-compact="tray"]');
    assert.equal(await layoutCompact.isChecked(), true);
    await reopen();
    assert.equal(await homeCompact.isChecked(), true);
    await openPage('layout');
    assert.equal(await layoutCompact.isChecked(), true);
    await page.getByRole('button', {name:'Reset layout'}).click();
    await builder.waitForFunction(() => !document.querySelector('[data-uq-compact]'));
    assert.equal(await layoutCompact.isChecked(), false);
    assert.equal(await homeCompact.isChecked(), false);
    await builder.evaluate(() => document.body.insertAdjacentHTML('beforeend', '<div data-component-key="row"><div id="row-header"><div><svg viewBox="0 0 24 24"></svg></div><div><div>row</div><div class="text-2xs">NUMBER</div></div><div><button data-slot="dropdown-menu-trigger" aria-label="Actions for row">⋮</button></div></div></div>'));
    const rowPreset = page.locator('#row-preset');
    assert.equal(await rowPreset.inputValue(), 'native');
    assert.equal(await page.locator('#row-sections').isVisible(), false);
    await rowPreset.selectOption('left');
    await builder.waitForSelector('#row-header[data-uq-row-layout] [data-uq-section="actions"][data-uq-slot="left"]');
    await page.getByRole('radio', {name:'Actions menu right'}).check();
    await builder.waitForSelector('#row-header [data-uq-section="actions"][data-uq-slot="right"]');
    await reopen();
    await openPage('layout');
    assert.equal(await rowPreset.inputValue(), 'custom');
    assert.equal(await page.getByRole('radio', {name:'Actions menu right'}).isChecked(), true);
    await goHome('layout');
    await openPage('style');
    await page.getByLabel('Style canvas components').uncheck();
    await builder.waitForFunction(() => !document.querySelector('[data-uq-row-layout]'));
    assert.equal(await rowPreset.isDisabled(), true);
    assert.match(await page.locator('.disabled-explanation:has(#row-preset) .disabled-hint').textContent(), /Component style → Style canvas components/);
    await page.getByRole('button', {name:'Reset style'}).click();
    await status('Saved');
    await builder.waitForSelector('#row-header[data-uq-row-layout]');
    await goHome('style');
    await openPage('layout');
    assert.equal(await rowPreset.inputValue(), 'custom', 'Reset style keeps the row layout');
    await page.getByRole('button', {name:'Reset layout'}).click();
    await status('Saved');
    assert.equal(await rowPreset.inputValue(), 'native');
    assert.equal(await builder.locator('[data-uq-row-layout]').count(), 0);
    await rowPreset.selectOption('custom');
    await builder.waitForSelector('#row-header[data-uq-row-layout] [data-uq-section="type"][data-uq-slot="left"]');
    assert.equal(await page.getByRole('radio', {name:'Type badge left'}).isChecked(), true, 'Custom starts with the type badge on the left');
    await rowPreset.selectOption('native');
    await builder.waitForFunction(() => !document.querySelector('[data-uq-row-layout]'));
    await builder.evaluate(() => document.querySelector('[data-component-key="row"]').remove());
    const guides = page.locator('input[data-appearance="containerGuides"]');
    assert.equal(await guides.isChecked(), false);
    await guides.check();
    await status('Saved');
    await reopen();
    await openPage('layout');
    assert.equal(await guides.isChecked(), true);
    await goHome('layout');
    await openPage('style');
    await page.getByLabel('Style canvas components').uncheck();
    await page.waitForSelector('.disabled-explanation.has-reason:has(input[data-appearance="containerGuides"])', {state:'attached'});
    assert.equal(await guides.isDisabled(), true);
    await page.getByLabel('Full colored borders').check();
    await page.getByRole('button', {name:'Reset style'}).click();
    await status('Saved');
    assert.equal(await guides.isChecked(), true, 'Reset style leaves layout settings untouched');
    assert.equal(await guides.isDisabled(), false);
    assert.equal(await page.getByLabel('Full colored borders').isChecked(), false);
    await page.getByLabel('Full colored borders').check();
    await status('Saved');
    await goHome('style');
    await openPage('layout');
    await page.getByRole('button', {name:'Reset layout'}).click();
    await status('Saved');
    assert.equal(await guides.isChecked(), false);
    assert.equal(await page.locator('input[data-appearance="borders"]').isChecked(), true, 'Reset layout leaves style settings untouched');
    await goHome('layout');
    await openPage('style');
    await page.getByRole('button', {name:'Reset style'}).click();
    await status('Saved');
    for (const name of ['symbols', 'icons', 'tiles', 'trayLabels', 'labels', 'accents', 'backgrounds', 'borders']) {
      await page.locator(`input[data-appearance="${name}"]`).uncheck();
    }
    await builder.waitForFunction(() => !document.querySelector('[data-uq-family],[data-uq-icon],[data-uq-icon-background],[data-uq-tile],[data-uq-label],[data-uq-symbol]'));
    await page.getByLabel('Colored icons', {exact:true}).check();
    await builder.waitForSelector('[data-uq-icon]');
    assert.equal(await builder.locator('svg').evaluate(element => getComputedStyle(element).backgroundColor), 'rgba(0, 0, 0, 0)');
    await page.getByLabel('Colored icons', {exact:true}).uncheck();
    await page.getByLabel('Tinted icon backgrounds', {exact:true}).check();
    await builder.waitForSelector('[data-uq-icon-background]');
    assert.equal(await builder.locator('[data-uq-icon]').count(), 0);
    await builder.evaluate(() => {
      const name = document.createElement('span');
      name.dataset.slot = 'tooltip-trigger';
      name.textContent = 'Number';
      document.querySelector('[data-tray-type]').append(name);
    });
    await page.getByLabel('Tinted icon backgrounds', {exact:true}).uncheck();
    await page.getByLabel('Colored sidebar names', {exact:true}).check();
    await builder.waitForSelector('[data-uq-label]');
    assert.equal(await builder.locator('[data-uq-label]').evaluate(element => getComputedStyle(element).color), 'rgb(147, 197, 253)');
    assert.equal(await builder.locator('[data-uq-icon],[data-uq-icon-background]').count(), 0);
    await page.getByRole('button', {name:'Reset style'}).click();
    await status('Saved');
    await page.keyboard.press('Escape');
    assert.equal(await isFocused('#open-style'), true);
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('#style-page').isVisible(), true);
    await goHome('style');
    await builder.waitForSelector('[data-uq-family="inputs"]');
    await styling.uncheck();
    await builder.waitForFunction(() => !document.querySelector('[data-uq-family]'));
    assert.equal(await homeCompact.isDisabled(), true);
    await reopen();
    assert.equal(await styling.isChecked(), false);
    await openPage('style');
    assert.equal(await page.locator('input[data-appearance="tray"]').isDisabled(), true);
    assert.match(await page.locator('.disabled-explanation:has(input[data-appearance="tray"]) .disabled-hint').textContent(), /Component styling on the home menu/);
    await goHome('style');
    await styling.check();
    await builder.waitForSelector('[data-uq-family="inputs"]');
    await builder.evaluate(() => {
      const group = document.createElement('div');
      group.id = 'group';
      group.setAttribute('aria-roledescription', 'draggable');
      group.innerHTML = '<div data-component-key="group" data-slot="collapsible-trigger"><div><svg viewBox="0 0 24 24"></svg></div><div class="text-2xs">FIELD GROUP</div></div><div data-component-key="child"><div><svg viewBox="0 0 24 24"></svg></div><div class="text-2xs">NUMBER</div></div>';
      // Unqork wraps every container frame in its collapsible root.
      const root = document.createElement('div');
      root.setAttribute('data-slot', 'collapsible');
      root.append(group);
      document.body.append(root);
    });
    await page.emulateMedia({colorScheme:'dark'});
    await openPage('style');
    await page.getByLabel('Full background accents').check();
    await builder.waitForSelector('[data-uq-background]');
    assert.equal(await builder.locator('[data-tray-type]').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(30, 58, 138)');
    await builder.waitForSelector('#group[data-uq-background]');
    assert.equal(await builder.locator('#group').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(76, 29, 149)');
    await page.getByLabel('Full colored borders').check();
    await builder.waitForSelector('#group[data-uq-border]');
    assert.equal(await builder.locator('[data-tray-type]').evaluate(element => getComputedStyle(element).borderTopColor), 'rgb(147, 197, 253)');
    await page.getByLabel('Full background accents').uncheck();
    await builder.waitForFunction(() => !document.querySelector('[data-uq-background]'));
    assert(await builder.locator('#group').getAttribute('data-uq-border') !== null);
    await reopen();
    await openPage('style');
    assert.equal(await page.getByLabel('Full colored borders').isChecked(), true);
    assert.equal(await page.getByLabel('Full background accents').isChecked(), false);
    await page.getByLabel('Full background accents').check();
    await builder.waitForSelector('[data-uq-background]');
    await builder.evaluate(() => document.documentElement.classList.remove('dark'));
    assert.equal(await builder.locator('[data-tray-type]').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(191, 219, 254)');
    assert.equal(await builder.locator('[data-tray-type]').evaluate(element => getComputedStyle(element).borderTopColor), 'rgb(30, 64, 175)');
    await goHome('style');
    await styling.uncheck();
    await builder.waitForFunction(() => !document.querySelector('[data-uq-background],[data-uq-border]'));
    await styling.check();
    await openPage('style');
    // Each group's swatch picks its color; the builder's backgrounds and borders follow it.
    const rgb = value => 'rgb(' + [1, 3, 5].map(index => parseInt(value.slice(index, index + 2), 16)).join(', ') + ')';
    const derivedTint = lib.load('component-colors').partner('light', 'ink', '#DC2626');
    const resetInputs = page.getByRole('button', {name:'Reset Input fields colors'});
    assert.equal(await resetInputs.isHidden(), true, 'Default colors have nothing to reset');
    await page.getByLabel('Input fields light foreground color', {exact:true}).fill('#dc2626');
    await builder.waitForFunction(value => getComputedStyle(document.querySelector('[data-tray-type]')).backgroundColor === value, rgb(derivedTint));
    assert.equal(await builder.locator('[data-tray-type]').evaluate(element => getComputedStyle(element).borderTopColor), 'rgb(220, 38, 38)');
    assert.equal(await page.getByLabel('Input fields light background color', {exact:true}).inputValue(), derivedTint.toLowerCase(), 'The background swatch shows the derived partner');
    // A picked background keeps two similar foregrounds apart.
    await page.getByLabel('Input fields light background color', {exact:true}).fill('#fef3c7');
    await builder.waitForFunction(() => getComputedStyle(document.querySelector('[data-tray-type]')).backgroundColor === 'rgb(254, 243, 199)');
    assert.equal(await builder.locator('[data-tray-type]').evaluate(element => getComputedStyle(element).borderTopColor), 'rgb(220, 38, 38)');
    assert.deepEqual((await page.evaluate(() => chrome.storage.local.get('componentColors'))).componentColors, { inputs:{ light:{ ink:'#DC2626', tint:'#FEF3C7' } } });
    assert.equal(await page.getByLabel('Input fields dark foreground color', {exact:true}).inputValue(), '#93c5fd', 'Dark colors stay separate');
    await resetInputs.click();
    await builder.waitForFunction(() => getComputedStyle(document.querySelector('[data-tray-type]')).backgroundColor === 'rgb(191, 219, 254)');
    assert.equal(await isFocused('[data-color="inputs-light-ink"]'), true, 'Focus returns to the first swatch after a reset');
    assert.equal(await resetInputs.isHidden(), true);
    await page.getByLabel('Grids dark background color', {exact:true}).fill('#0c4a6e');
    await page.getByRole('button', {name:'Reset Grids colors'}).waitFor();
    await page.getByRole('button', {name:'Reset style'}).click();
    await builder.waitForSelector('[data-uq-family="inputs"]');
    await builder.waitForFunction(() => !document.querySelector('[data-uq-background],[data-uq-border]'));
    assert.deepEqual((await page.evaluate(() => chrome.storage.local.get('componentColors'))).componentColors, {}, 'Reset style restores default colors');
    assert.equal(await page.getByRole('button', {name:'Reset Grids colors'}).isHidden(), true);
    assert.equal(await page.getByLabel('Full colored borders').isChecked(), false);
    assert.equal(await page.getByLabel('Full background accents').isChecked(), false);
    await page.screenshot({path:path.resolve(__dirname, '../artifacts/popup-dark.png')});
    await page.emulateMedia({colorScheme:'light'});
    await page.screenshot({path:path.resolve(__dirname, '../artifacts/popup-light.png')});
    await builder.evaluate(() => {
      document.body.insertAdjacentHTML('beforeend', '<div class="unqorkio-form"></div>');
      window.testSubmission = { data:{} };
      window.angular = { element:() => ({ scope:() => ({ submission:window.testSubmission, form:{} }) }) };
    });
    const executeQuickAction = lib.load('quick-actions').runQuickAction;
    await page.exposeFunction('fixtureQuickAction', request => builder.evaluate(executeQuickAction, request));
    await page.evaluate(() => {
      chrome.tabs.query = async () => [{ id:7, url:'https://another-tenant.unqork.io/ide/builder/test' }];
      chrome.scripting.executeScript = async injection => [{ result:await window.fixtureQuickAction(injection.args[0]) }];
    });
    await goHome('style');
    // Home logs directly when the page is reachable, without leaving the home menu.
    await builder.evaluate(() => {
      window.logged = 0;
      const log = console.log;
      console.log = (...args) => { window.logged++; log(...args); };
    });
    await page.getByRole('button', {name:'Log page data', exact:true}).click();
    await page.waitForFunction(() => document.getElementById('home-log-status').textContent.includes('Logged'));
    assert.equal(await page.locator('#home-log-status').getAttribute('data-state'), 'success');
    assert(await builder.evaluate(() => window.logged > 0), 'Home log writes to the page console');
    assert.equal(await home.isVisible(), true);
    await openPage('quick');
    await page.getByRole('tab', {name:'Data', exact:true}).click();
    await page.getByLabel('Property name (exact key)').fill('premium');
    await page.getByLabel('Value', {exact:true}).fill('42');
    await page.getByRole('radio', {name:'Number', exact:true}).check();
    await page.getByRole('button', {name:'Update property', exact:true}).click();
    assert.match(await page.locator('#confirmation-text').innerText(), /PRODUCTION ENVIRONMENT/);
    assert.equal(await isFocused('#cancel-action'), true);
    await page.screenshot({path:path.resolve(__dirname, '../artifacts/production-guard.png')});
    // Escape dismisses the pending confirmation before it leaves the page.
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#debug-confirmation').isHidden(), true);
    assert.equal(await page.locator('#quick-page').isVisible(), true);
    await page.getByRole('button', {name:'Update property', exact:true}).click();
    await page.getByRole('button', {name:'Change anyway', exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#panel-data .debug-feedback').textContent.includes('updated in memory'));
    assert.equal(await builder.evaluate(() => window.testSubmission.data.premium), 42);
    await page.screenshot({path:path.resolve(__dirname, '../artifacts/quick-light.png')});
    await page.emulateMedia({colorScheme:'dark'});
    await page.screenshot({path:path.resolve(__dirname, '../artifacts/quick-dark.png')});
    await page.emulateMedia({colorScheme:'light'});
    await goHome('quick');
    // Import & export round-trips real storage through the clipboard and a downloaded file.
    await openPage('transfer');
    // Record the text on its way to the real clipboard, which automation cannot read from an extension origin.
    await page.evaluate(() => {
      const write = navigator.clipboard.writeText.bind(navigator.clipboard);
      navigator.clipboard.writeText = text => { window.copiedText = text; return write(text); };
    });
    await page.getByRole('button', {name:'Copy JSON', exact:true}).click();
    await page.waitForFunction(() => document.getElementById('export-status').textContent === 'Settings copied as JSON.');
    const copied = JSON.parse(await page.evaluate(() => window.copiedText));
    const saved = await page.evaluate(() => chrome.storage.local.get(['appearance', 'floating']));
    assert.equal(copied.settings.appearance.compact, saved.appearance.compact);
    assert.equal(copied.extensionVersion, require('../package.json').version);
    const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', {name:'Download file', exact:true}).click()]);
    assert.match(download.suggestedFilename(), /^unqlock-settings-\d{4}-\d{2}-\d{2}\.json$/);
    const file = JSON.parse(fs.readFileSync(await download.path(), 'utf8'));
    assert.deepEqual(file.settings, copied.settings);
    file.settings.appearance.compact = !copied.settings.appearance.compact;
    file.settings.floating.position = 'top-left';
    await page.getByLabel('Paste exported JSON').fill(JSON.stringify(file));
    await page.getByRole('button', {name:'Review pasted JSON', exact:true}).click();
    await page.getByRole('checkbox', {name:'Floating launcher', exact:true}).uncheck();
    await page.getByRole('button', {name:'Import selected', exact:true}).click();
    await page.waitForFunction(() => document.getElementById('import-status').textContent.startsWith('Imported'));
    const imported = await page.evaluate(() => chrome.storage.local.get(['appearance', 'floating']));
    assert.equal(imported.appearance.compact, file.settings.appearance.compact);
    assert.deepEqual(imported.floating, saved.floating, 'Unchosen sections stay unchanged');
    assert.equal(await homeCompact.isChecked(), file.settings.appearance.compact, 'Home switch shows the imported value');
    await page.screenshot({path:path.resolve(__dirname, '../artifacts/transfer.png')});
    console.log('PASS: Import & export copies, downloads and imports real extension storage.');
    console.log('PASS: packaged quick-actions UI, home logging and page function with fixture-provided tab and scripting APIs; toolbar permission grant requires manual verification.');
    console.log('PASS: unpacked extension loads with no manifest errors; page navigation and focus, bound home switches, split resets, launcher badge label, content-script injection, storage persistence and light/dark popup rendering.');
    console.log('PASS: independent background/border controls, light/dark computed colors, nested group frames, persistence, disable cleanup and reset defaults.');
  } finally { await context.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
