const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
(async () => {
  const dom = new JSDOM('<div class="unqorkio-form"></div>', { url:'https://example.test/app', runScripts:'outside-only' });
  const window = dom.window;
  const submission = { data:{} };
  let executions = 0;
  let components = [{ key:'run', execute:async () => { executions++; } }];
  window.angular = { element:() => ({ scope:() => ({ submission, form:{} }), injector:() => { throw new Error('No cache'); } }) };
  window.UnqorkioUtils = { eachComponent:(_forms, visit) => components.forEach(visit) };
  const execute = window.eval(require('./lib.cjs').bundle('lib/quick-actions.ts', 'quick') + '\nquick.runQuickAction;');
  const run = overrides => execute({ url:window.location.href, action:'set', key:'test', value:'', type:'text', confirmed:true, ...overrides });
  assert((await run({})).ok);
  assert.equal(submission.data.test, '');
  assert((await run({ value:'0', type:'number' })).ok);
  assert.equal(submission.data.test, 0);
  for (const value of ['', 'Infinity', 'nope']) assert.equal((await run({ value, type:'number' })).ok, false);
  assert((await run({ value:'{"active":false}', type:'object' })).ok);
  assert.equal(submission.data.test.active, false);
  for (const value of ['null', 'true', '{bad}']) assert.equal((await run({ value, type:'object' })).ok, false);
  for (const key of ['', ' ', '__proto__', 'constructor', 'prototype']) assert.equal((await run({ key })).ok, false);
  assert.equal((await run({ confirmed:false })).ok, false);
  assert.equal((await run({ production:true })).ok, false);
  assert.equal((await run({ production:true, productionConfirmed:true, blockProduction:true })).ok, false);
  assert((await run({ production:true, productionConfirmed:true })).ok);
  assert.equal((await run({ url:'https://example.test/changed' })).ok, false);
  assert((await run({ key:'literal.dot', value:'yes' })).ok);
  assert.equal(submission.data['literal.dot'], 'yes');
  assert((await run({ action:'remove' })).ok);
  assert.equal((await run({ action:'remove' })).ok, false);
  assert((await run({ action:'trigger', key:'run' })).ok);
  assert.equal(executions, 1);
  components.push(components[0]);
  assert.equal((await run({ action:'trigger', key:'run' })).ok, false);
  components = [{ key:'run', execute:async () => { throw new Error('Failed'); } }];
  assert.equal((await run({ action:'trigger', key:'run' })).ok, false);
  let logs = 0;
  window.console = { log:() => logs++, group:() => {}, groupEnd:() => {}, warn:() => {} };
  assert((await run({ action:'log', confirmed:false })).ok);
  assert((await run({ action:'log', style:'object' })).ok);
  assert.equal(logs, 2);
  window.document.body.innerHTML = '';
  assert.equal((await run({})).ok, false);
  dom.window.close();
  console.log('PASS: page action validation, mutation, execution failures and logging.');
})().catch(error => { console.error(error); process.exitCode = 1; });
